spring.application.name=TestModule


#judge0
judge0.api.url=https://judge0-ce.p.rapidapi.com
judge0.api.key=${JUDGE0_API_KEY}
judge0.api.host=judge0-ce.p.rapidapi.com


#gemini
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent