import { useState } from 'react';
import { Sliders, RefreshCw, Sparkles, FileCode, CheckCircle2, Download, Globe, Check, Rocket } from 'lucide-react';
import { SearchableSelect } from '@/components/SearchableSelect';
import { TOPICS } from '@/types';
import type { GeneratedQuestion } from './admin.types';

interface AdminGeneratorTabProps {
  onPublishQuestion?: (q: GeneratedQuestion) => void;
  onPublishAllQuestions?: (qs: GeneratedQuestion[]) => void;
}

export function AdminGeneratorTab({
  onPublishQuestion,
  onPublishAllQuestions,
}: AdminGeneratorTabProps) {
  const [genTopic, setGenTopic] = useState<string>('Array');
  const [genCount, setGenCount] = useState<number>(4);
  const [genRatioEasy, setGenRatioEasy] = useState<number>(50);
  const [genRatioMedium, setGenRatioMedium] = useState<number>(30);
  const [genRatioHard, setGenRatioHard] = useState<number>(20);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedExam, setGeneratedExam] = useState<GeneratedQuestion[] | null>(null);

  // Track published question IDs locally
  const [publishedIds, setPublishedIds] = useState<Set<string>>(new Set());
  const [publishBannerMsg, setPublishBannerMsg] = useState<string | null>(null);

  const handleGenerateExam = () => {
    setIsGenerating(true);
    setPublishBannerMsg(null);
    setPublishedIds(new Set());
    setTimeout(() => {
      const mockGenerated: GeneratedQuestion[] = Array.from({ length: genCount }).map((_, idx) => {
        const diff: 'Easy' | 'Medium' | 'Hard' =
          idx === 0
            ? 'Easy'
            : idx < Math.ceil(genCount * 0.6)
              ? 'Medium'
              : 'Hard';
        return {
          id: `gen-q-${Date.now()}-${idx + 1}`,
          title: `Bài ${idx + 1}: ${genTopic} - Kỹ thuật ${diff === 'Easy' ? 'cơ bản' : diff === 'Medium' ? 'xử lý tối ưu' : 'nâng cao'}`,
          topic: genTopic,
          difficulty: diff,
          starterCode: `function solution${idx + 1}(input) {\n  // Starter code generated by AI for ${genTopic}\n  return null;\n}`,
          description: `Bài tập thực hành sinh bởi AI về chủ đề ${genTopic} (${diff}). Đạt chuẩn định dạng và có test case mẫu.`,
          isPublic: false,
        };
      });
      setGeneratedExam(mockGenerated);
      setIsGenerating(false);
    }, 1200);
  };

  const handlePublishSingle = (q: GeneratedQuestion) => {
    setPublishedIds((prev) => new Set(prev).add(q.id));
    onPublishQuestion?.(q);
    setPublishBannerMsg(`🎉 Đã công khai bài "${q.title}" vào danh sách bài học của sinh viên!`);
  };

  const handlePublishAll = () => {
    if (!generatedExam) return;
    const allIds = new Set(generatedExam.map((q) => q.id));
    setPublishedIds(allIds);
    onPublishAllQuestions?.(generatedExam);
    setPublishBannerMsg(`🚀 Đã xuất bản thành công toàn bộ ${generatedExam.length} bài tập mới lên hệ thống cho người dùng học!`);
  };

  return (
    <div className="admin-tab-content">
      <div className="admin-header-row">
        <div>
          <h1 className="admin-page-title">Generate Đề & Quản lý Xuất bản Bài tập</h1>
          <p className="admin-page-sub">
            Cấu hình tham số để AI sinh bộ đề bài tập ngẫu nhiên. Bấm <strong>"Public bài này"</strong> hoặc <strong>"Public toàn bộ"</strong> để công khai bài cho sinh viên học.
          </p>
        </div>
      </div>

      {publishBannerMsg && (
        <div
          style={{
            background: 'rgba(120, 211, 158, 0.12)',
            border: '1px solid rgba(120, 211, 158, 0.35)',
            color: '#78d39e',
            padding: '12px 18px',
            borderRadius: '10px',
            marginBottom: '20px',
            fontSize: '14px',
            fontWeight: 500,
            display: 'flex',
            alignItems: 'center',
            gap: '10px',
          }}
        >
          <CheckCircle2 size={18} />
          {publishBannerMsg}
        </div>
      )}

      <div className="admin-generator-layout">
        {/* Panel điều khiển tham số Generator */}
        <div className="admin-card-box">
          <h3 className="admin-card-title">
            <Sliders size={18} /> Thiết Lập Tiêu Chí Sinh Đề
          </h3>

          <div className="profile-form">
            <div className="auth-field">
              <span className="auth-label" style={{ marginBottom: '6px' }}>Chủ đề chính</span>
              <SearchableSelect
                options={TOPICS.map((t) => ({ label: t, value: t }))}
                value={genTopic}
                onChange={(val) => setGenTopic(val)}
                showSearch={true}
              />
            </div>

            <label className="auth-field">
              <span className="auth-label">Tổng số bài tập ({genCount} bài)</span>
              <input
                type="range"
                min={2}
                max={10}
                value={genCount}
                onChange={(e) => setGenCount(Number(e.target.value))}
                style={{ accentColor: '#5e8dfa' }}
              />
            </label>

            <div className="admin-ratio-box">
              <span className="auth-label" style={{ marginBottom: '10px', display: 'block' }}>
                Tỷ lệ phân bổ độ khó bài tập
              </span>

              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '8px' }}>
                <div className="ratio-input">
                  <span style={{ color: '#78d39e', fontSize: '12px', fontWeight: 600 }}>Dễ (%)</span>
                  <input
                    type="number"
                    value={genRatioEasy}
                    onChange={(e) => setGenRatioEasy(Number(e.target.value))}
                  />
                </div>
                <div className="ratio-input">
                  <span style={{ color: '#f5c95d', fontSize: '12px', fontWeight: 600 }}>Trung bình (%)</span>
                  <input
                    type="number"
                    value={genRatioMedium}
                    onChange={(e) => setGenRatioMedium(Number(e.target.value))}
                  />
                </div>
                <div className="ratio-input">
                  <span style={{ color: '#f08a8a', fontSize: '12px', fontWeight: 600 }}>Khó (%)</span>
                  <input
                    type="number"
                    value={genRatioHard}
                    onChange={(e) => setGenRatioHard(Number(e.target.value))}
                  />
                </div>
              </div>
            </div>

            <button
              className="assessment-primary"
              style={{ width: '100%', justifyContent: 'center', marginTop: '12px' }}
              onClick={handleGenerateExam}
              disabled={isGenerating}
            >
              {isGenerating ? (
                <>
                  <RefreshCw size={16} className="spin" /> Đang tổng hợp bài...
                </>
              ) : (
                <>
                  <Sparkles size={16} /> Generate bộ đề ngay
                </>
              )}
            </button>
          </div>
        </div>

        {/* Panel kết quả preview bộ đề được generate */}
        <div className="admin-card-box">
          <h3 className="admin-card-title" style={{ justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <FileCode size={18} /> Preview & Quản Lý Xuất Bản
            </span>
            {generatedExam && (
              <button
                className="assessment-primary"
                onClick={handlePublishAll}
                style={{ fontSize: '12px', padding: '5px 12px', gap: '6px' }}
                title="Công khai tất cả các bài này vào kho bài tập của học viên"
              >
                <Rocket size={14} /> Public toàn bộ ({generatedExam.length} bài)
              </button>
            )}
          </h3>

          {generatedExam ? (
            <div className="admin-gen-results">
              <div className="gen-results-header">
                <span className="gen-exam-tag">
                  <CheckCircle2 size={14} /> Bộ đề {genTopic} ({generatedExam.length} bài)
                </span>
                <button className="history-view-btn">
                  <Download size={14} /> Xuất file JSON
                </button>
              </div>

              <div className="gen-question-list">
                {generatedExam.map((q) => {
                  const isPub = publishedIds.has(q.id);
                  return (
                    <div className="gen-question-item" key={q.id} style={{ borderColor: isPub ? '#78d39e44' : undefined }}>
                      <div className="gen-q-head" style={{ justifyContent: 'space-between', alignItems: 'center' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                          <strong>{q.title}</strong>
                          <span
                            className="practice-difficulty"
                            style={{
                              color:
                                q.difficulty === 'Easy'
                                  ? '#78d39e'
                                  : q.difficulty === 'Medium'
                                    ? '#f5c95d'
                                    : '#f08a8a',
                            }}
                          >
                            {q.difficulty}
                          </span>
                        </div>

                        {/* Public action button */}
                        {isPub ? (
                          <span
                            style={{
                              fontSize: '11px',
                              padding: '3px 10px',
                              borderRadius: '12px',
                              background: '#78d39e18',
                              color: '#78d39e',
                              border: '1px solid #78d39e44',
                              fontWeight: 600,
                              display: 'flex',
                              alignItems: 'center',
                              gap: '4px',
                            }}
                          >
                            <Check size={12} /> Đã Public cho HSSV
                          </span>
                        ) : (
                          <button
                            type="button"
                            className="assessment-primary"
                            onClick={() => handlePublishSingle(q)}
                            style={{ fontSize: '11px', padding: '4px 10px', gap: '4px' }}
                            title="Đăng công khai bài này cho người dùng học"
                          >
                            <Globe size={12} /> Public bài này
                          </button>
                        )}
                      </div>
                      <pre className="gen-code-preview">
                        <code>{q.starterCode}</code>
                      </pre>
                    </div>
                  );
                })}
              </div>
            </div>
          ) : (
            <div className="admin-empty-preview">
              <Sparkles size={40} strokeWidth={1.2} style={{ color: '#3a4d7a', marginBottom: '12px' }} />
              <p style={{ color: '#7d8599', fontSize: '14px', margin: 0 }}>
                Nhấn nút <strong>Generate bộ đề ngay</strong> để xem danh sách bài tập được sinh ngẫu nhiên theo tiêu chí và công khai lên hệ thống.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
